#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01). Let’s also add other subdomains to make our life easier, and write a Bash script that will display information about subdomains.
funct_domain () {
    subdomain="$2"
    domain="$1"
	dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", domain, $4, $5 }' domain="$subdomain"
}
if [ "$2" ];
then
	for sub_domain in "www" "lb-01" "web-01" "web-02"
	do
		if [ "$2" == "$sub_domain" ]
		then
			funct_domain "$1" "$sub_domain"
		fi
	done
else
    for sub_domain in "www" "lb-01" "web-01" "web-02"
	do
	    funct_domain "$1" "$sub_domain"
	done
fi
