#!/usr/bin/env bash
if [ $# -lt 3 ]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -o StrictHostkeyChecking=no -i "$4" "$1" "$3@$2":~/
	#scp -F "$1" "$2" "$3" -i "$4" 
fi

#scp somfile.html        ubuntu@35.632.6358:~/
#scp /path/to/local/file remote_user@remote_host:/path/to/remote/file
#scp [switch] [source content location] [destination content location]