#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 
#page that contains the string Ceci n'est pas une page.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "45i error_page 404 /custom_404.html;" /etc/nginx/sites-enabled/default
service nginx restart
