#!/usr/bin/env bash
#The file /etc/passwd has already been covered in a previous project and you should be familiar with it. Today we will make up a story based on it. Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS using a Format
dicetcpsswd="/etc/passwd"
while IFS=":" read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND_SHELL
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "$dicetcpsswd"
