#!/usr/bin/env bash
#using sed to change ip 
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
sed -i '/.* facebook.com$/d' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
